# Generated by Django 3.0.8 on 2020-07-13 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('job', models.CharField(default='', max_length=40)),
                ('authCode', models.CharField(max_length=40)),
                ('activated', models.BooleanField(default=False)),
                ('quizMaxScore', models.IntegerField(default=0)),
                ('unlockedTalks', models.CharField(max_length=40)),
                ('isActive', models.BooleanField(default=True)),
                ('isAdmin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer1', models.TextField()),
                ('answer2', models.TextField()),
                ('answer3', models.TextField()),
                ('correctAnswer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeakersSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Talks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('img', models.ImageField(upload_to='')),
                ('lockedImg', models.ImageField(upload_to='')),
                ('header', models.TextField()),
                ('subheader', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('cover', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
                ('header', models.TextField()),
                ('info1', models.TextField()),
                ('info2', models.TextField()),
                ('mainVideo', models.TextField()),
                ('video1', models.TextField()),
                ('video2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WhatsNext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsNext', models.TextField()),
                ('platformUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PlatformUser')),
            ],
        ),
    ]
