# Generated by Django 3.0.5 on 2020-07-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuser',
            name='authCode',
            field=models.CharField(default='default', max_length=40),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='email',
            field=models.EmailField(default='default@nomail.com', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='job',
            field=models.CharField(default='default', max_length=40),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='name',
            field=models.CharField(default='default', max_length=40),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='password',
            field=models.CharField(default='default', max_length=40),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='unlockedTalks',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='trends',
            name='header',
            field=models.TextField(blank=True, null=True),
        ),
    ]
