# Generated by Django 3.0.5 on 2020-07-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200716_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuser',
            name='email',
            field=models.EmailField(default='default@nomail.com', max_length=40),
        ),
    ]
