# Generated by Django 3.0.5 on 2020-07-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200720_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformuser',
            name='authCode',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='password',
        ),
    ]
