# Generated by Django 3.0.5 on 2020-07-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200722_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuariosConectados', models.IntegerField(default=0, max_length=40)),
                ('usuariosRegistradosQueSeLogearon', models.CharField(default=0, max_length=40)),
                ('talk1TotalReproductions', models.IntegerField(default=0)),
                ('talk2TotalReproductions', models.IntegerField(default=0)),
                ('talk3TotalReproductions', models.IntegerField(default=0)),
                ('talk4TotalReproductions', models.IntegerField(default=0)),
                ('talk5TotalReproductions', models.IntegerField(default=0)),
                ('talk6TotalReproductions', models.IntegerField(default=0)),
                ('callToAction', models.IntegerField(default=0)),
                ('rebote', models.IntegerField(default=0)),
                ('visitasTotales', models.IntegerField(default=0)),
                ('visitasOtherPages', models.IntegerField(default=0)),
                ('quizTotalesAmount', models.IntegerField(default=0)),
                ('quizCalificationAcumulative', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='platformuser',
            name='hasLoggedInAtLeastOne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='talk1PlayTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='talk1UpTo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='talk2PlayTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='talk2UpTo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='talk3PlayTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='talk3UpTo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='talk4PlayTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='talk4UpTo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='talk5PlayTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='talk5UpTo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='talk6PlayTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='talk6UpTo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='timeBeingOnWebsite',
            field=models.IntegerField(default=0),
        ),
    ]
