# Generated by Django 3.0.5 on 2020-07-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200722_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticas',
            name='usuariosConectados',
            field=models.IntegerField(default=0),
        ),
    ]
