# Generated by Django 3.0.5 on 2020-07-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200722_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticas',
            name='usuariosRegistradosQueSeLogearon',
            field=models.IntegerField(default=0),
        ),
    ]
