# Generated by Django 3.0.5 on 2020-07-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200722_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticas',
            name='timeInPage',
            field=models.IntegerField(default=0),
        ),
    ]
